MODEL:
  PRETRAIN_CHOICE: "imagenet"
  METRIC_LOSS_TYPE: "triplet"
  IF_LABELSMOOTH: "on"
  IF_WITH_CENTER: "no"
  NAME: "ViT-B-16"
  STRIDE_SIZE: [16, 16]

  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 1.0
  SUPCON_LOSS_WEIGHT: 0.5

  PROMPTSG:
    CMT_DEPTH: 2
    INVERSION_LAYERS: 2
    INVERSION_DROPOUT: 0.1
    TRAIN_MODE: "composed"
    TEST_MODE: "simplified"
    COMPOSED_TEMPLATE: "A photo of a X person"
    SIMPLE_TEMPLATE: "A photo of a person"
    FREEZE_TEXT_ENCODER: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: "softmax_triplet"
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  IMS_PER_BATCH: 64

  VISUAL_BASE_LR: 0.000005
  NEW_MODULE_BASE_LR: 0.00005

  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001

  MAX_EPOCHS: 60
  WARMUP_FACTOR: 0.1
  WARMUP_EPOCHS: 5

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10

  STEPS: [20, 40]
  GAMMA: 0.1

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: ""
  NECK_FEAT: "before"
  FEAT_NORM: "yes"
DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: datasets/dataset
OUTPUT_DIR: ('logs/promptsg_market_vit/')